{% set name = "plumed" %}
{% set version = environ['VERSION'] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..
  # Tar is preferred, but a symlink therein crashes windows builds. Git is ok.
  # url: https://github.com/plumed/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: f4cf55c63a6798a0607f4e47eeeee7c1bc191668772c83ce4dabf3a5ba407426

build:
  number: 0
  skip: True  # [win]
  skip: True  # [py<35]
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - m2-bash  # [win]
    - m2-curl  # [win]
    - m2-findutils  # [win]
    - m2-diffutils  # [win]
    - m2-gawk  # [win]
    - m2-grep  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
    - m2-which  # [win]
    - m2-tar  # [win]
    - zlib
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
#    - ccache-toolchain
  host:
    - python
    - pip
    - cython
    - zlib
    - m2w64-binutils  # [win]
    - m2w64-gcc  # [win]
    - m2w64-tools-git  # [win]

  run:
    - python
    - zlib

test:
  # TODO. In principle these could be the official regtests.
  imports:
    - plumed
  commands:
    - plumed info --root
    - plumed info --version
    - plumed info --long-version
    - python -c "import plumed; p=plumed.Plumed(); print(p)"

about:
  home: http://www.plumed.org/
  license: LGPL
  license_file: COPYING.LESSER
  summary: 'Free energy calculations in molecular systems'
  description: >
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://plumed.github.io/doc-v2.5/user-doc/html/index.html
  dev_url: https://github.com/plumed/plumed2

