package:
  name: plumed
  version: 2.8

source:
  git_url: ..\..

build:
  number: 0
  skip: false
  string: testing
# Most programs should link libplumedWrapper.a so that libplumedKernel.so will be loaded
# with dlopen. There is no need for pinning thus.
# Programs linking libplumed.so should pin to min_pin='x.x', max_pin='x'.
# Programs linking libplumedKernel.so should pin to min_pin='x.x.x'. max_pin='x.x.x'.


requirements:
  build:
    - m2w64-gcc  # [win]
    - autotools_clang_conda  # [win]
  host:
    - fftw   
    - gsl  
    - zlib
  run:
    - m2-gawk  # [win]
    - m2-msys2-runtime  # [win]
    - m2w64-gcc-libs  # [win]
    - m2w64-zlib  # [win]

test:
  commands:
    - plumed info --root
    - plumed info --long-version

about:
  home: http://www.plumed.org/
  license: LGPL-3.0-only
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Free energy calculations in molecular systems
  description: |
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://www.plumed.org/doc
  dev_url: https://github.com/plumed/plumed2

extra:
  recipe-maintainers:
    - tonigi
