name: W64 build

on:
  push:
  pull_request:


jobs:
  w64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    - run: conda info
    - run: conda build w64/recipe
